# Generated by Django 5.2 on 2025-05-18 17:38

from django.db import migrations

def add_initial_data(apps, schema_editor):
    Role = apps.get_model('mbooks', 'Role')
    Role.objects.create(name='customer')
    Role.objects.create(name='manager')
    Role.objects.create(name='administrator')

class Migration(migrations.Migration):

    dependencies = [
        ('mbooks', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]