# Generated by Django 5.2 on 2025-05-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbooks', '0002_auto_20250518_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sold',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
