# Generated by Django 5.2 on 2025-05-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbooks', '0003_book_sold'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
    ]
