# Generated by Django 5.2 on 2025-05-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbooks', '0004_alter_cart_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
