# Generated by Django 5.2 on 2025-05-28 21:30

from django.db import migrations

def add_initial_data(apps, schema_editor):
    OrderStatus = apps.get_model('mbooks', 'OrderStatus')
    OrderStatus.objects.create(name='Оформлен')
    OrderStatus.objects.create(name='Готов к получению')
    OrderStatus.objects.create(name='Получен')
    OrderStatus.objects.create(name='Отказ')

class Migration(migrations.Migration):

    dependencies = [
        ('mbooks', '0006_alter_book_price'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
