# Generated by Django 5.2 on 2025-06-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbooks', '0007_fill_order_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available',
            field=models.SmallIntegerField(default=1, help_text='1 или True – Книга доступна. 0 или False – книга удалена'),
        ),
    ]
