# Generated by Django 5.2 on 2025-06-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbooks', '0008_book_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2025),
            preserve_default=False,
        ),
    ]
