# Generated by Django 5.2 on 2025-06-03 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mbooks', '0009_book_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
    ]
