# Generated by Django 5.2 on 2025-06-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbooks', '0010_remove_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
